PhotoOrder.Web/Models/Kep.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PhotoOrder.Web.Models
{
    public class Kep
    {
        [Display(Name = "Kép azonosító")]
        [Required]
        public int Id { get; set; }

        [Display(Name = "Rendelési kód")]
        [Required]
        [StringLength(10)]
        public string RendelesiKod { get; set; }

        [Display(Name = "Fotós")]
        [Required]
        public string Fotos { get; set; }

        [Display(Name = "Elérési út")]
        [Required]
        [StringLength(128, MinimumLength = 4)]
        public string EleresiUt { get; set; }

        [Display(Name = "Tájolás")]
        [Required]
        public string Tajolas { get; set; }
    }
}

PhotoOrder.Web/Models/KepViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PhotoOrder.Web.Models
{
    public class KepViewModel
    {
        public Kep EditedKep { get; set; }

        public List<Kep> Kepek { get; set; }
    }
}

PhotoOrder.Web/Controllers/KepController.cs
using AutoMapper;
using PhotoOrder.Data;
using PhotoOrder.Logic;
using PhotoOrder.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhotoOrder.Web.Controllers
{
    public class KepController : Controller
    {
        ILogic logic;
        IMapper mapper;
        KepViewModel vm;

        public KepController()
        {
            this.logic = new PhotoOrderLogic(new PhotoOrderModel());
            this.mapper = MapperFactory.CreateMapper();

            this.vm = new KepViewModel();
            vm.EditedKep = new Models.Kep();

            // Data.képek lekérése
            var Kepek = logic.GetKepek().ToList();

            // Átkonvertálás form modelekké
            vm.Kepek = mapper.Map<IList<Data.Kep>, List<Models.Kep>>(Kepek);

        }

        /// <summary>
        /// A data PhotoOrder.Web.képekből a PhotoOrder.Web.képeket csinál.
        /// </summary>
        /// <param name="id">A kép id-je</param>
        /// <returns>Visszaad egy képet.</returns>
        private Models.Kep GetKepModel(int id)
        {
            var kep = logic.GetKepek().FirstOrDefault(k => k.kep_id == id);
            return this.mapper.Map<Data.Kep, Models.Kep>(kep);
        }

        // GET: Kep
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("KepIndex", this.vm);
        }

        // GET: Kep/Details/5
        public ActionResult Details(int id)
        {
            return View("KepDetails", this.GetKepModel(id));
        }
        
        // GET: Kep/Edit/5
        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedKep = GetKepModel(id);
            return View("KepIndex", this.vm);
        }

        // POST: Kep/Edit/5
        [HttpPost]
        public ActionResult Edit(Models.Kep kep, string editAction)
        {
            if(ModelState.IsValid && kep != null)
            {
                if(editAction == "AddNew")
                {
                    // A logic add nem adatokat vár, hanem már kész példányt.
                    // A MapperFactory-ban megírt reverseMap alapján viszont vissza tudunk nyerni egy ilyen példányt
                    Data.Kep dKep = mapper.Map<Models.Kep, Data.Kep>(kep);

                    logic.AddKep(dKep);
                }
                else
                {
                    Data.Kep dKep = mapper.Map<Models.Kep, Data.Kep>(kep);
                    bool success = this.logic.UpdateKep((int)dKep.kep_id, dKep.rendelesi_kod, dKep.eleresi_ut, dKep.fotos, dKep.tajolas ?? 0);
                    if (!success)
                        TempData["editResult"] = "Edit fail";
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditedKep = kep;
                return View("KepIndex", this.vm);
            }
        }

        // GET: Kep/Delete/5
        public ActionResult Delete(int id)
        {
            // A törlés nem bool-t ad vissza, hanem kivételt dob a logicban.
            try
            {
                this.logic.DeleteKep(this.logic.GetKepek().FirstOrDefault(k => k.kep_id == id));
                TempData["editResult"] = "Sikeres törlés";
            }
            catch
            {
                TempData["editResult"] = "Sikertelen törlés";
            }
            
            return RedirectToAction(nameof(Index));
        }
    }
}

PhotoOrder.Web/Views/Kep/KepDetails.cshtml
#@model PhotoOrder.Web.Models.Kep
@{
    ViewBag.Title = "KepDetails";
}

<h2>Képek</h2>

@Html.ActionLink("Vissza a listához", "Index")

<table>
    <tr>
        <td>A kép id-je</td>
        <td>@Model.Id</td>
    </tr>

    <tr>
        <td>@Html.DisplayNameFor(m => m.RendelesiKod)</td>
        <td>@Html.DisplayFor(m => m.RendelesiKod)</td>
    </tr>

    <tr>
        <td>@Html.DisplayNameFor(m => m.Fotos)</td>
        <td>@Html.DisplayFor(m => m.Fotos)</td>
    </tr>

    <tr>
        <td>@Html.DisplayNameFor(m => m.EleresiUt)</td>
        <td>@Html.DisplayFor(m => m.EleresiUt)</td>
    </tr>

    <tr>
        <td>@Html.DisplayNameFor(m => m.Tajolas)</td>
        <td>@Html.DisplayFor(m => m.Tajolas)</td>
    </tr>



</table>

PhotoOrder.Web/Views/Kep/KepEdit.cshtml
@model PhotoOrder.Web.Models.Kep

<h2>Kép szerkesztése</h2>

@using (Html.BeginForm("Edit", "Kep"))
{
    <p style="color: red">@Html.ValidationSummary()</p>

    @Html.AntiForgeryToken();

    @Html.HiddenFor(m => m.Id)
    @Html.Hidden("editAction", ViewData["editAction"].ToString())

    <div class="editor-label">@Html.LabelFor(m => m.RendelesiKod)</div>
    <div class="editor-field">@Html.EditorFor(m => m.RendelesiKod)</div>

    <div class="editor-label">@Html.LabelFor(m => m.EleresiUt)</div>
    <div class="editor-field">@Html.EditorFor(m => m.EleresiUt)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Fotos)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Fotos)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Tajolas) (álló/fekvő)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Tajolas)</div>

    <input type="submit" value="Kész"/>
}

PhotoOrder.Web/Views/Kep/KepIndex.cshtml
@model PhotoOrder.Web.Models.KepViewModel
@{
    ViewBag.Title = "KepIndex";
}

<h2>Képek indexe</h2>
<h3>Magyarázat</h3>
<p>
    Az adatbázis rendszer egy leegyszerűsítése egy <a href="https://asulifotosa.hu/rendeles/">webshopnak</a> amit a prog 3 félévessel egyidőben kellett kiépítenem.
    Egy fotós cég iskolákban/óvodákban készít képeket, és minden gyerekhez egy rendelési kódot rendel. A szülők 
    ezeket a kódokat kapják kézbe minden fotózás után. Ezeket a kódokat be kell írniuk a weboldalra, amely kilistázza a gyermekükről
    készült összes képet, és tudnak rendelni.
</p>

<p style="color:red; font-weight: bold;">@TempData["editResult"]</p>

@Html.Partial("KepEdit", Model.EditedKep)

@Html.Partial("KepList", Model.Kepek)

PhotoOrder.Web/Views/Kep/KepList.cshtml
@model IEnumerable<PhotoOrder.Web.Models.Kep>

<h2>
    Képek listája
</h2>

@if (Model.Count() == 0)
{
    <p>Nincsenek még képek.</p>
}
else
{
    <table border="1">
        <tr>
            <td>Kép</td>
            <td>@Html.DisplayNameFor(m => m.First().RendelesiKod)</td>
            <td>Adatlap</td>
            <td>Törlés</td>
            <td>Szerkesztés</td>
        </tr>
        @foreach (var item in Model)
        {
    <tr>
        <td><img src="@Html.DisplayFor(m => item.EleresiUt)" alt="@Html.DisplayFor(m => item.EleresiUt)" /></td>
        <td>@Html.DisplayFor(m => item.RendelesiKod)</td>
        <td>@Html.ActionLink("[Megtekintés]", "Details", new { id = item.Id })</td>
        <td>@Html.ActionLink("[Törlés]", "Delete", new { id = item.Id })</td>
        <td>@Html.ActionLink("[Szerkesztés]", "Edit", new { id = item.Id })</td>
    </tr>
        }
    </table>
}